name: Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Listar todos os arquivos do projeto
        run: ls -la

      - name: Transferir os arquivos para a VM
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.IP }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "app/**"       # tudo dentro de app/
          target: "/var/www/html"
          strip_components: 1    # descarta a pasta app/
          overwrite: true

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key
          ssh-keyscan -H ${{ secrets.IP }} >> ~/.ssh/known_hosts
      - name: Run Composer Install
        run: ssh -i ~/.ssh/private_key ec2-user@${{ secrets.IP }} "cd /var/www/html && composer install --no-dev --optimize-autoloader"
      - name: Run NPM Install
        run: ssh -i ~/.ssh/private_key ec2-user@${{ secrets.IP }} "cd /var/www/html && npm install --production"